# Test Raffia task status display scenarios

# ---
# SLAM_TASKNAME: Status Test Scenarios
# SLAM_Q: [ triage, play ]
# ---

---
- hosts: "{{ NODE }}"
  tasks:
    - debug: var=ansible_host

    - name: Success
      command: /bin/true

    - name: Fail
      command: /bin/false
      ignore_errors: yes

    - name: Skipped (no results)
      command: /bin/true
      when: true == false

    - name: Partial Skipped (some results)
      command: /bin/true
      when: ansible_host | search("[13579]$")

    - name: Partial Success
      command: >
        {{ (ansible_host | search("[13579]$")) | ternary('/bin/true', '/bin/false') }}
      ignore_errors: yes
