# Test Raffia task status display scenarios

# ---
# SLAM_TASKNAME: Status Test Scenarios
# SLAM_Q: [ triage, play ]
# ---

---
- hosts: "{{ NODE }}"
  tasks:
    - name: Success
      command: /bin/true

    - name: Fail
      command: /bin/false

    - name: Skipped (no results)
      command: /bin/true
      when: "{{ true == false }}"

    - name: Partial Skipped (some results)
      command: /bin/true
      when: ansible_hostname | match("[13579]$")

    - name: Partial Success
      command: >
        {{ (ansible_hostname | match("[13579]$")) | ternary('/bin/true', '/bin/false') }}
