# Test Raffia task status display scenarios

# ---
# SLAM_TASKNAME: Status Test Scenarios default strategy
# SLAM_Q: [ triage, play ]
# ---

---
- hosts: "{{ NODE }}"
  tasks:
    - debug: var=ansible_host

    - name: Success
      command: /bin/true

    - name: Fail
      command: /bin/false
      ignore_errors: yes

    - name: Skipped
      command: /bin/true
      when: true == false

    - name: Partial Skipped
      command: /bin/true
      when: ansible_host | search("[13579]$")

    - name: Partial Success
      command: >
        {{ (ansible_host | search("[13579]$")) | ternary('/bin/true', '/bin/false') }}
      ignore_errors: yes

    - name: Partial Success with skipped
      command: >
        {{ (ansible_host | search("[13579]$")) | ternary('/bin/true', '/bin/false') }}
      ignore_errors: yes
      when: ansible_host | search("[013-9]$")

    - name: This task deliberately has a veeeeeeeeeeeeeeeeeeery looooooooooooooooooooooooong task name to force ellipsis clipping in diagram
      command: /bin/true

    - name: Fail with stderr
      command: 'echo "stderr goes here" >&2; /bin/false'

    - name: Fail with stdout
      command: 'echo "stdout goes here"; /bin/false'

    - name: Fail with stderr & stdout
      command: 'echo "stderr goes here" >&2; echo "stdout goes here"; /bin/false'

- hosts: UNREACHABLE
  tasks:
    - debug: msg="Reached!!!"
