# Test Raffia task status display scenarios

# ---
# SLAM_TASKNAME: Status Test Scenarios
# SLAM_Q: [ triage, play ]
# ---

---
- hosts: "{{ NODE }}"
  tasks:
    - name: Success
      command: /bin/true

    - name: Fail
      command: /bin/false

    - name: Skipped
      command: /bin/true
      when: "{{ true == false }}"
